/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IGMP, IGMPInterface } from "../IGMP";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "receiveMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGMP__factory {
  static readonly abi = _abi;
  static createInterface(): IGMPInterface {
    return new Interface(_abi) as IGMPInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IGMP {
    return new Contract(address, _abi, runner) as unknown as IGMP;
  }
}
